### ISSUE TITLE
这是怎么回事？

### ISSUE THREAD

**Issue by an010-pipixia** [alibaba/web-editor#110]
![image](https://user-images.githubusercontent.com/72434237/168528063-396a7f4d-2ec0-4e4b-bd4f-11cace309d9c.png)

**Comment by an010-pipixia** [comment]
Obtaining file:///D:/web-editor-master
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      C:\python39\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'author-email' will not
 be supported in future versions. Please use the underscore name 'author_email' instead
        warnings.warn(
      C:\python39\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'home-page' will not be
 supported in future versions. Please use the underscore name 'home_page' instead
        warnings.warn(
      C:\python39\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' will
 not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      WARNING: The wheel package is not available.
      ERROR:root:Error parsing
      Traceback (most recent call last):
        File "d:\web-editor-master\.eggs\pbr-5.9.0-py3.9.egg\pbr\core.py", line 111, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
        File "d:\web-editor-master\.eggs\pbr-5.9.0-py3.9.egg\pbr\util.py", line 272, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "d:\web-editor-master\.eggs\pbr-5.9.0-py3.9.egg\pbr\hooks\__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "d:\web-editor-master\.eggs\pbr-5.9.0-py3.9.egg\pbr\hooks\base.py", line 27, in run
          self.hook()
        File "d:\web-editor-master\.eggs\pbr-5.9.0-py3.9.egg\pbr\hooks\metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
        File "d:\web-editor-master\.eggs\pbr-5.9.0-py3.9.egg\pbr\packaging.py", line 872, in get_version
          raise Exception("Versioning for this project requires either an sdist"
      Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository.
It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.
VersionInfo. Project name weditor was given, but was not able to be found.
      error in setup command: Error parsing D:\web-editor-master\setup.cfg: Exception: Versioning for this project requi
res either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch betwee
n the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name weditor was given, but w
as not able to be found.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by wJJh** [comment]
pip3 install weditor==0.6.4

**Comment by coolbiubiu** [comment]
安装低版本的，或者使用这两个命令：git clone https://github.com/openatx/weditor pip3 install -e weditor
