### ISSUE TITLE
Pypi上的0.6.5版本能否发布一个.whl

### ISSUE THREAD

**Issue by edsion1107** [alibaba/web-editor#120]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      D:\Users\80370454\.local\pipx\shared\Lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
        warnings.warn(
      D:\Users\80370454\.local\pipx\shared\Lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'home-page' will not be supported in future versions. Please use the underscore name 'home_page' instead
        warnings.warn(
      D:\Users\80370454\.local\pipx\shared\Lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      D:\Users\80370454\.local\pipx\shared\Lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Error parsing
      Traceback (most recent call last):
        File "d:\users\80370454\appdata\local\temp\pip-req-build-2jbrrwvj\.eggs\pbr-5.10.0-py3.9.egg\pbr\core.py", line 111, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
        File "d:\users\80370454\appdata\local\temp\pip-req-build-2jbrrwvj\.eggs\pbr-5.10.0-py3.9.egg\pbr\util.py", line 272, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "d:\users\80370454\appdata\local\temp\pip-req-build-2jbrrwvj\.eggs\pbr-5.10.0-py3.9.egg\pbr\hooks\__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "d:\users\80370454\appdata\local\temp\pip-req-build-2jbrrwvj\.eggs\pbr-5.10.0-py3.9.egg\pbr\hooks\base.py", line 27, in run
          self.hook()
        File "d:\users\80370454\appdata\local\temp\pip-req-build-2jbrrwvj\.eggs\pbr-5.10.0-py3.9.egg\pbr\hooks\metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
        File "d:\users\80370454\appdata\local\temp\pip-req-build-2jbrrwvj\.eggs\pbr-5.10.0-py3.9.egg\pbr\packaging.py", line 860, in get_version
          version = _get_version_from_pkg_metadata(package_name)
        File "d:\users\80370454\appdata\local\temp\pip-req-build-2jbrrwvj\.eggs\pbr-5.10.0-py3.9.egg\pbr\packaging.py", line 828, in _get_version_from_pkg_metadata
          pkg_metadata = email.message_from_file(pkg_metadata_file)
        File "D:\Users\80370454\AppData\Local\Programs\Python\Python39\lib\email\__init__.py", line 54, in message_from_file
          return Parser(*args, **kws).parse(fp)
        File "D:\Users\80370454\AppData\Local\Programs\Python\Python39\lib\email\parser.py", line 53, in parse
          data = fp.read(8192)
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 825: illegal multibyte sequence
      error in setup command: Error parsing D:\Users\80370454\AppData\Local\Temp\pip-req-build-2jbrrwvj\setup.cfg: UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 825: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Cannot determine package name from spec 'D:\\Users\\80370454\\Desktop\\weditor-0.6.5.tar.gz'. Check package spec for
errors.

我试了本地build一个whl是可以安装的，但是从.tar.gz安装失败

**Comment by coolbiubiu** [comment]
用这个两个命令：git clone https://github.com/openatx/weditor; pip3 install -e weditor

**Comment by taylorsweeft13** [comment]
win10 按这个改一下utf-8 我可以安装
https://blog.csdn.net/weixin_51597238/article/details/125786390

**Comment by chenmonster** [comment]
> win10 按这个改一下utf-8 我可以安装 https://blog.csdn.net/weixin_51597238/article/details/125786390

还是用这个方法解决了

**Comment by codeskyblue** [comment]
现在有更好的替代品了， https://uiauto.dev

weditor后期就不更新了
