### ISSUE TITLE
AttributeError：'MockStdout' object has no attribute 'flush'

### ISSUE THREAD

**Issue by Keanu-teh** [alibaba/web-editor#131]
weditor的console显示结果如下：

Set environment and prepare d = u2.connect()Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\17720\AppData\Local\Programs\Python\Python39\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\17720\AppData\Local\Programs\Python\Python39\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\17720\AppData\Local\Programs\Python\Python39\lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\17720\AppData\Local\Programs\Python\Python39\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
AttributeError: 'MockStdout' object has no attribute 'flush'[Finished 0s]

python是3.9.13，weditor是0.6.5，连接的是mumu模拟器，并且每次运行代码console都执行不出结果

**Comment by Keanu-teh** [comment]
看1.19发的pull request里面更新的ipyshell-console.py，直接解决

**Comment by leeyorke** [comment]
https://github.com/alibaba/web-editor/pull/128/commits/75bdf2a6e285c47ca095b1a87f7ddb30ec1e8143;
将更新flush函数直接写进老的ipyshell-console.py文件即可，在103行
