### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by fatonnsmahr** [alibaba/web-editor#134]
Collecting weditor
  Using cached weditor-0.6.8.tar.gz (2.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Error parsing
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-5psw8ktl\normal\Lib\site-packages\pbr\core.py", line 105, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-5psw8ktl\normal\Lib\site-packages\pbr\util.py", line 272, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-5psw8ktl\normal\Lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-5psw8ktl\normal\Lib\site-packages\pbr\hooks\base.py", line 27, in run
          self.hook()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-5psw8ktl\normal\Lib\site-packages\pbr\hooks\metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-5psw8ktl\normal\Lib\site-packages\pbr\packaging.py", line 862, in get_version
          version = _get_version_from_pkg_metadata(package_name)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-5psw8ktl\normal\Lib\site-packages\pbr\packaging.py", line 830, in _get_version_from_pkg_metadata
          pkg_metadata = email.message_from_file(pkg_metadata_file)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\email\__init__.py", line 54, in message_from_file
          return Parser(*args, **kws).parse(fp)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\email\parser.py", line 53, in parse
          data = fp.read(8192)
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 645: illegal multibyte sequence
      error in setup command: Error parsing C:\Users\Administrator\AppData\Local\Temp\pip-install-r8cipwh2\weditor_bcaaaebe605041409c3da3018f948ae4\setup.cfg: UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 645: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by LeanFly** [comment]
克隆代码到本地，用管理员权限打开终端，进入到代码目录，执行 安装：python setup.py install

**Comment by LeanFly** [comment]
克隆代码到本地，用管理员权限打开终端，进入到代码目录，执行 安装：python setup.py install

**Comment by IDhammaI** [comment]
Traceback (most recent call last):
  File "C:\Users\IDhammaI\Downloads\web-editor\setup.py", line 9, in <module>
    setup(setup_requires=['pbr'], python_requires='>=3.6', pbr=True)
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\pbr\packaging.py", line 243, in run
    return du_install.install.run(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\_distutils\command\install.py", line 708, in run
    self.run_command(cmd_name)
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\IDhammaI\AppData\Local\anaconda3\envs\Spider\Lib\site-packages\pbr\packaging.py", line 509, in run
    get_script_args = easy_install.get_script_args
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'setuptools.command.easy_install' has no attribute 'get_script_args'
