### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by dingshaohua-cn** [alibaba/web-editor#136]
```
Traceback (most recent call last):
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\__init__.py", line 27, in <module>
    from . import urllib3
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\urllib3\connectionpool.py", line 29, in <module>
    from .connection import (
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\urllib3\connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\urllib3\util\__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\urllib3\util\connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\urllib3\util\wait.py", line 1, in <module>
    from .selectors import (
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\urllib3\util\selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Scripts\weditor.exe\__main__.py", line 4, in <module>
  File "D:\pub-code\web-editor\weditor\__main__.py", line 26, in <module>
    import requests
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\__init__.py", line 60, in <module>
    from . import utils
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\compat.py", line 11, in <module>
    from .packages import chardet
  File "C:\Users\boringsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\packages\__init__.py", line 29, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```

**Comment by jeremyru** [comment]
安装urllib3，版本最好低一点1.24.3
