### ISSUE TITLE
连接手机时报错：AttributeError: 'MockStdout' object has no attribute 'flush'

### ISSUE THREAD

**Issue by bmjssd** [alibaba/web-editor#139]
Set environment and prepare d = u2.connect()Traceback (most recent call last):
    exec(ccode, globals)
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'MockStdout' object has no attribute 'flush'[Finished 0.002s]

有什么解决办法吗？

**Comment by pinkman199810** [comment]
add codes
![image](https://github.com/alibaba/web-editor/assets/65639657/3eb17457-9900-4765-88cd-6eede19ac1ea)
or upgrade latest package
