### ISSUE TITLE
iOS connect正常，但是dump hierarchy报错，瞬间xctrunner quited with result:

### ISSUE THREAD

**Issue by Hello-Allen** [alibaba/web-editor#151]
tidevice 0.12.9
wda 8.5.2
ios 14.4
macOS 14
weditor 0.7.2
u2 3.0.8

weditor启动后，点击iOS设备connect按钮连接，一切正常
![image](https://github.com/alibaba/web-editor/assets/15259557/98edbe75-2d53-4f6f-8ca4-4774b5f6283e)

当点击dump hierarchy按钮时，控制台秒弹退出日志
![image](https://github.com/alibaba/web-editor/assets/15259557/02633595-4fdf-413b-a0be-970c4888e239)

接着就失败叻。
[E 240417 20:11:11 web:1871] Uncaught exception GET /api/v2/devices/iOS%3A/hierarchy (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v2/devices/iOS%3A/hierarchy', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 715, in urlopen
        httplib_response = self._make_request(
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 416, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
        self.send(msg)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
        self.connect()
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/requests_usbmux.py", line 54, in connect
        conn = _device.create_inner_connection(int(port))
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/usbmux.py", line 238, in create_inner_connection
        raise MuxConnectError(
    wda.exceptions.MuxConnectError: device port:8100 is not ready

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/requests/adapters.py", line 486, in send
        resp = conn.urlopen(
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 799, in urlopen
        retries = retries.increment(
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/urllib3/util/retry.py", line 550, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/urllib3/packages/six.py", line 769, in reraise
        raise value.with_traceback(tb)
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 715, in urlopen
        httplib_response = self._make_request(
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 416, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
        self.send(msg)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
        self.connect()
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/requests_usbmux.py", line 54, in connect
        conn = _device.create_inner_connection(int(port))
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/usbmux.py", line 238, in create_inner_connection
        raise MuxConnectError(
    urllib3.exceptions.ProtocolError: ('Connection aborted.', MuxConnectError('device port:8100 is not ready'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/weditor/web/handlers/page.py", line 97, in get
        self.write(d.dump_hierarchy2())
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/weditor/web/device.py", line 116, in dump_hierarchy2
        uidumplib.get_ios_hierarchy(self._client, self.__scale),
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/weditor/web/uidumplib.py", line 139, in get_ios_hierarchy
        sourcejson = d.source(format='json')
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/__init__.py", line 536, in source
        return self.http.get('source?format=' + format).value
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/utils.py", line 47, in _inner
        return fn(*args, **kwargs)
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/__init__.py", line 462, in _fetch
        response = httpdo(url, method, data, timeout)
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/__init__.py", line 131, in httpdo
        return _unsafe_httpdo(url, method, data, timeout)
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/wda/__init__.py", line 158, in _unsafe_httpdo
        response = request_session.request(method,
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "/Users/helloallen/Library/Python/3.9/lib/python/site-packages/requests/adapters.py", line 501, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', MuxConnectError('device port:8100 is not ready'))
[E 240417 20:11:11 web:2344] 500 GET /api/v2/devices/iOS%3A/hierarchy (::1) 18.59ms

其他iOS 15 16设备均无异常

求大佬解答

**Comment by codeskyblue** [comment]
换个新的wda看看呢

**Comment by Hello-Allen** [comment]
> 换个新的wda看看呢

从wda5.6~最新8.2都复现改问题。。
