### ISSUE TITLE
dump fail

### ISSUE THREAD

**Issue by lijingchun0** [alibaba/web-editor#81]
- macos：big sur
- python: version: 3.8
- weditor version: 0.6.1
- drivers: HUAWEI MATE 30
- android 10
```
[E 201125 10:29:57 web:1789] Uncaught exception GET /api/v1/devices/android%3A/screenshot (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v1/devices/android%3A/screenshot', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/uiautomator2/__init__.py", line 862, in screenshot
        return Image.open(buff).convert("RGB")
      File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2943, in open
        raise UnidentifiedImageError(
    PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x10355d220>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.8/site-packages/weditor/web/handlers/page.py", line 301, in get
        d.screenshot().convert("RGB").save(buffer, format='JPEG')
      File "/usr/local/lib/python3.8/site-packages/weditor/web/device.py", line 28, in screenshot
        return self._d.screenshot()
      File "<decorator-gen-10>", line 2, in screenshot
      File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
        return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
      File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
        return f()
      File "/usr/local/lib/python3.8/site-packages/uiautomator2/__init__.py", line 867, in screenshot
        if d.settings['fallback_to_blank_screenshot']:
    NameError: name 'd' is not defined
[E 201125 10:29:57 web:2239] 500 GET /api/v1/devices/android%3A/screenshot (::1) 2054.89ms
```

![image](https://user-images.githubusercontent.com/26979634/100175534-8ce59780-2f09-11eb-8675-3fdf4332f373.png)

**Comment by lijingchun0** [comment]
fix   i have a proxy - _ -
